services:
  churchcrm:
    image: git.serigrafika.sk/thasko/churchcrm-docker-modern:7.3.1
    container_name: churchcrm-app
    restart: unless-stopped
    ports:
      - '30086:80'
    environment:
      - MYSQL_DB_HOST=churchcrm-db
      - MYSQL_DB_NAME=churchcrm
      - MYSQL_DB_USER=${MYSQL_USER}
      - MYSQL_DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      churchcrm-db:
        condition: service_healthy

  churchcrm-db:
    image: mariadb:11.4
    container_name: churchcrm-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=churchcrm
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - healthcheck.sh
        - '--connect'
        - '--innodb_initialized'
      timeout: 5s
    volumes:
      - /mnt/apps/churchcrm_db:/var/lib/mysql
