services:
  churchcrm:
    image: git.serigrafika.sk/thasko/churchcrm-docker-modern:7.3.1
    container_name: churchcrm-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - MYSQL_DB_HOST=churchcrm-db
      - MYSQL_DB_NAME=churchcrm
      - MYSQL_DB_USER=churchcrm
      - MYSQL_DB_PASSWORD=${MYSQL_PASSWORD:-churchcrm_pass}
    depends_on:
      churchcrm-db:
        condition: service_healthy

  churchcrm-db:
    image: mariadb:11.4
    container_name: churchcrm-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=churchcrm
      - MYSQL_USER=churchcrm
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-churchcrm_pass}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_pass}
    volumes:
      - /mnt/vault/apps/churchcrm/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
